"""empty message

Revision ID: 040d24e96c1a
Revises: b13aacaa6769
Create Date: 2025-10-22 13:13:06.235605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040d24e96c1a'
down_revision = 'b13aacaa6769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('last_read_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('current_read_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('used_water_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate_per_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reading_id'], ['meter_readings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_reading_id'), ['reading_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_reading_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))

    op.drop_table('invoices')
    # ### end Alembic commands ###
