"""empty message

Revision ID: 1a2420f22632
Revises: 8c82a4670be3
Create Date: 2025-10-13 12:34:30.513238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2420f22632'
down_revision = '8c82a4670be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('capacity_m3_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_production_date', sa.Date(), nullable=True),
    sa.Column('last_volume_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_sources')
    # ### end Alembic commands ###
