"""add receipt payment method

Revision ID: 2dfb29089c6c
Revises: b176a599ad14
Create Date: 2026-06-29 13:30:01.588472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfb29089c6c'
down_revision = 'b176a599ad14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=32), nullable=False, server_default=sa.text("'cash'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
