"""empty message

Revision ID: 33f19828011f
Revises: ec5b78f1ee84
Create Date: 2025-10-21 14:49:10.028798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f19828011f'
down_revision = 'ec5b78f1ee84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_code', sa.String(length=20), nullable=True),
    sa.Column('area_name', sa.String(length=120), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_areas_area_code'), ['area_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_areas_area_code'))

    op.drop_table('service_areas')
    # ### end Alembic commands ###
