"""empty message

Revision ID: 57f7ab330f47
Revises: c5ebdcc81eab
Create Date: 2025-10-20 14:49:02.732268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f7ab330f47'
down_revision = 'c5ebdcc81eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('raw_water_m3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('treated_water_m3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_used', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('ph_level', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('turbidity_ntu', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('chlorine_mgL', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_records')
    # ### end Alembic commands ###
