"""add partial invoice payment tracking

Revision ID: 596ef39a3ff7
Revises: b483f58fecb7
Create Date: 2026-06-29 12:06:22.411759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596ef39a3ff7'
down_revision = 'b483f58fecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0.00')))
        batch_op.add_column(sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0.00')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('balance_due')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###

