"""empty message

Revision ID: 89f3695f18ac
Revises: c1a7a5fb9d20
Create Date: 2026-07-12 11:25:10.015384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89f3695f18ac'
down_revision = 'c1a7a5fb9d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_column('pressure_bar')
        batch_op.drop_column('length_km')
        batch_op.drop_column('flow_rate_lps')

    with op.batch_alter_table('storage_tank', schema=None) as batch_op:
        batch_op.drop_column('last_inflow_date')
        batch_op.drop_column('last_outflow_m3')
        batch_op.drop_column('last_outflow_date')
        batch_op.drop_column('last_inflow_m3')
        batch_op.drop_column('current_level_m3')

    with op.batch_alter_table('treatment_records', schema=None) as batch_op:
        batch_op.drop_column('ph_level')
        batch_op.drop_column('raw_water_m3')
        batch_op.drop_column('chlorine_mgL')
        batch_op.drop_column('turbidity_ntu')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    with op.batch_alter_table('water_sources', schema=None) as batch_op:
        batch_op.drop_column('last_volume_m3')
        batch_op.drop_column('last_production_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_production_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('last_volume_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', mysql.VARCHAR(length=120), nullable=True))

    with op.batch_alter_table('treatment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turbidity_ntu', mysql.DECIMAL(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('chlorine_mgL', mysql.DECIMAL(precision=6, scale=3), nullable=True))
        batch_op.add_column(sa.Column('raw_water_m3', mysql.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ph_level', mysql.DECIMAL(precision=4, scale=2), nullable=True))

    with op.batch_alter_table('storage_tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_level_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('last_inflow_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('last_outflow_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('last_outflow_m3', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('last_inflow_date', sa.DATE(), nullable=True))

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_rate_lps', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('length_km', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('pressure_bar', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
