"""empty message

Revision ID: 9e3b5b5d4ffd
Revises: 33f19828011f
Create Date: 2025-10-21 15:44:39.541686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3b5b5d4ffd'
down_revision = '33f19828011f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('service_area_id', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.String(length=120), nullable=False),
    sa.Column('pipe_diameter_mm', sa.Float(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('flow_rate_lps', sa.Float(), nullable=True),
    sa.Column('pressure_bar', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('last_supply_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_area_id'], ['service_areas.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['storage_tank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipelines')
    # ### end Alembic commands ###
