"""empty message

Revision ID: b13aacaa6769
Revises: 5879ec32b579
Create Date: 2025-10-21 21:06:25.367724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13aacaa6769'
down_revision = '5879ec32b579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('last_read_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('current_read_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('used_water_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate_per_m3', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'reading_date', name='uq_meter_date')
    )
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_readings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_readings_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_readings_reading_date'), ['reading_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_readings_reading_date'))
        batch_op.drop_index(batch_op.f('ix_meter_readings_meter_id'))
        batch_op.drop_index(batch_op.f('ix_meter_readings_customer_id'))

    op.drop_table('meter_readings')
    # ### end Alembic commands ###
