"""add staff profile fields

Revision ID: b483f58fecb7
Revises: 
Create Date: 2026-06-28 18:04:28.932762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b483f58fecb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('service_area_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_service_area_id'), ['service_area_id'], unique=False)
        batch_op.create_foreign_key(None, 'service_areas', ['service_area_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_service_area_id'))
        batch_op.drop_column('service_area_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('job_title')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
