"""empty message

Revision ID: b830646bb08e
Revises: ab7f1c9d4e12
Create Date: 2026-07-05 12:15:26.219214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b830646bb08e'
down_revision = 'ab7f1c9d4e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('meter_readings_ibfk_3'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meter_readings_recorded_by_user_id'))
        batch_op.drop_column('recorded_by_user_id')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('receipts_ibfk_3'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_receipts_received_by_user_id'))
        batch_op.drop_column('received_by_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('receipts_ibfk_3'), 'users', ['received_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_receipts_received_by_user_id'), ['received_by_user_id'], unique=False)

    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('meter_readings_ibfk_3'), 'users', ['recorded_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_meter_readings_recorded_by_user_id'), ['recorded_by_user_id'], unique=False)

    # ### end Alembic commands ###
