"""empty message

Revision ID: c5ebdcc81eab
Revises: 1a2420f22632
Create Date: 2025-10-20 13:18:31.001794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ebdcc81eab'
down_revision = '1a2420f22632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chemical_name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('default_dose_mgL', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical')
    # ### end Alembic commands ###
