"""empty message

Revision ID: ec5b78f1ee84
Revises: 57f7ab330f47
Create Date: 2025-10-21 12:48:18.796711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5b78f1ee84'
down_revision = '57f7ab330f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_tank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tank_name', sa.String(length=120), nullable=False),
    sa.Column('capacity_m3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_level_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_inflow_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_outflow_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_inflow_date', sa.Date(), nullable=True),
    sa.Column('last_outflow_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_tank')
    # ### end Alembic commands ###
