"""empty message

Revision ID: fcc38a3e23de
Revises: 040d24e96c1a
Create Date: 2025-10-22 15:46:34.199426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcc38a3e23de'
down_revision = '040d24e96c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('reading_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_read_m3',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('current_read_m3',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('used_water_m3',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('rate_per_m3',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_invoices_reading_id'))
        batch_op.create_index(batch_op.f('ix_invoices_reading_id'), ['reading_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('invoices_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'meter_readings', ['reading_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoices_ibfk_2'), 'meter_readings', ['reading_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_invoices_reading_id'))
        batch_op.create_index(batch_op.f('ix_invoices_reading_id'), ['reading_id'], unique=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('rate_per_m3',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=False)
        batch_op.alter_column('used_water_m3',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=False)
        batch_op.alter_column('current_read_m3',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=False)
        batch_op.alter_column('last_read_m3',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=False)
        batch_op.alter_column('reading_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
